# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - modelmanager

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_a5549d4b9ba14c13a30f85c2ef099bcc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f439472976654d4cb471cc4fef3e2ad3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_a5549d4b9ba14c13a30f85c2ef099bcc }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'modelmanager'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8d0be5499ca2476ea2ee03126ca981eb }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_a5549d4b9ba14c13a30f85c2ef099bcc }}/appsvc/staticsite:${{ github.sha }}'