# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - modelmanager

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://modelmanagerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_870c284ba79d438d87c5cc74d7d10750 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e6f32a12fdff4f36a1f8e8ad6c02a789 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: modelmanagerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_870c284ba79d438d87c5cc74d7d10750 }}/modelmanager:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'modelmanager'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_706802917fba4476a598cb1b78afe228 }}
        images: 'modelmanagerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_870c284ba79d438d87c5cc74d7d10750 }}/modelmanager:${{ github.sha }}'